#!/bin/sh
# File generated by ocamlbuild

cd /home/ag/Documents/VOQC_PythonBindings/SQIR/VOQC/extraction/lib

rm -f list.cmi
# Also clean the script itself
rm -f /home/ag/Documents/VOQC_PythonBindings/SQIR/VOQC/extraction/lib/_build/sanitize.sh
